import type { Provider } from "./models"

export const FREE_MODELS_PROVIDER_ID = "free-all"

export const FREE_MODELS_PROVIDER: Provider = {
  id: FREE_MODELS_PROVIDER_ID,
  name: "Free All Models (Tamamen Ücretsiz)",
  env: ["FREE_ALL_MODELS_API_KEY", "FREE_MODELS_API_KEY", "OPENROUTER_API_KEY"],
  api: "https://text.pollinations.ai/openai",
  npm: "@ai-sdk/openai-compatible",
  models: {
    "deepseek-r1": {
      id: "deepseek-r1",
      name: "DeepSeek R1 (671B Düşünce - Bedava)",
      release_date: "2025-01-20",
      attachment: false,
      reasoning: true,
      temperature: true,
      tool_call: true,
      cost: { input: 0, output: 0, cache_read: 0, cache_write: 0 },
      limit: { context: 131072, output: 8192 },
      modalities: { input: ["text"], output: ["text"] },
      provider: { npm: "@ai-sdk/openai-compatible", api: "https://text.pollinations.ai/openai" },
    },
    "deepseek-v3": {
      id: "deepseek",
      name: "DeepSeek V3 (Chat & Kod - Bedava)",
      release_date: "2024-12-26",
      attachment: false,
      reasoning: false,
      temperature: true,
      tool_call: true,
      cost: { input: 0, output: 0, cache_read: 0, cache_write: 0 },
      limit: { context: 131072, output: 8192 },
      modalities: { input: ["text"], output: ["text"] },
      provider: { npm: "@ai-sdk/openai-compatible", api: "https://text.pollinations.ai/openai" },
    },
    "gemini-2.0-flash": {
      id: "gemini",
      name: "Google Gemini 2.0 Flash (Hızlı - Bedava)",
      release_date: "2025-02-05",
      attachment: true,
      reasoning: false,
      temperature: true,
      tool_call: true,
      cost: { input: 0, output: 0, cache_read: 0, cache_write: 0 },
      limit: { context: 1048576, output: 8192 },
      modalities: { input: ["text", "image"], output: ["text"] },
      provider: { npm: "@ai-sdk/openai-compatible", api: "https://text.pollinations.ai/openai" },
    },
    "gemini-2.0-thinking": {
      id: "gemini-thinking",
      name: "Google Gemini 2.0 Thinking (Düşünce Modu - Bedava)",
      release_date: "2025-01-20",
      attachment: true,
      reasoning: true,
      temperature: true,
      tool_call: true,
      cost: { input: 0, output: 0, cache_read: 0, cache_write: 0 },
      limit: { context: 1048576, output: 8192 },
      modalities: { input: ["text", "image"], output: ["text"] },
      provider: { npm: "@ai-sdk/openai-compatible", api: "https://text.pollinations.ai/openai" },
    },
    "llama-3.3-70b": {
      id: "llama-3.3-70b",
      name: "Meta Llama 3.3 70B (Güçlü Açık Kaynak - Bedava)",
      release_date: "2024-12-06",
      attachment: false,
      reasoning: false,
      temperature: true,
      tool_call: true,
      cost: { input: 0, output: 0, cache_read: 0, cache_write: 0 },
      limit: { context: 131072, output: 8192 },
      modalities: { input: ["text"], output: ["text"] },
      provider: { npm: "@ai-sdk/openai-compatible", api: "https://text.pollinations.ai/openai" },
    },
    "qwen-2.5-coder-32b": {
      id: "qwen-coder",
      name: "Qwen 2.5 Coder 32B (Yazılım Uzmanı - Bedava)",
      release_date: "2024-11-12",
      attachment: false,
      reasoning: false,
      temperature: true,
      tool_call: true,
      cost: { input: 0, output: 0, cache_read: 0, cache_write: 0 },
      limit: { context: 131072, output: 8192 },
      modalities: { input: ["text"], output: ["text"] },
      provider: { npm: "@ai-sdk/openai-compatible", api: "https://text.pollinations.ai/openai" },
    },
    "mistral-large": {
      id: "mistral",
      name: "Mistral Large (Avrupa AI - Bedava)",
      release_date: "2024-11-18",
      attachment: false,
      reasoning: false,
      temperature: true,
      tool_call: true,
      cost: { input: 0, output: 0, cache_read: 0, cache_write: 0 },
      limit: { context: 131072, output: 8192 },
      modalities: { input: ["text"], output: ["text"] },
      provider: { npm: "@ai-sdk/openai-compatible", api: "https://text.pollinations.ai/openai" },
    },
    "phi-4": {
      id: "phi-4",
      name: "Microsoft Phi-4 (14B Mantık/Matematik - Bedava)",
      release_date: "2025-01-09",
      attachment: false,
      reasoning: true,
      temperature: true,
      tool_call: true,
      cost: { input: 0, output: 0, cache_read: 0, cache_write: 0 },
      limit: { context: 16384, output: 4096 },
      modalities: { input: ["text"], output: ["text"] },
      provider: { npm: "@ai-sdk/openai-compatible", api: "https://text.pollinations.ai/openai" },
    },
    "gpt-4o-mini": {
      id: "openai",
      name: "OpenAI GPT-4o Mini (Pollinations Free Tier - Bedava)",
      release_date: "2024-07-18",
      attachment: true,
      reasoning: false,
      temperature: true,
      tool_call: true,
      cost: { input: 0, output: 0, cache_read: 0, cache_write: 0 },
      limit: { context: 128000, output: 8192 },
      modalities: { input: ["text", "image"], output: ["text"] },
      provider: { npm: "@ai-sdk/openai-compatible", api: "https://text.pollinations.ai/openai" },
    },
    "claude-3.5-haiku": {
      id: "claude-haiku",
      name: "Claude 3.5 Haiku (Pollinations Free Tier - Bedava)",
      release_date: "2024-10-22",
      attachment: true,
      reasoning: false,
      temperature: true,
      tool_call: true,
      cost: { input: 0, output: 0, cache_read: 0, cache_write: 0 },
      limit: { context: 200000, output: 8192 },
      modalities: { input: ["text", "image"], output: ["text"] },
      provider: { npm: "@ai-sdk/openai-compatible", api: "https://text.pollinations.ai/openai" },
    },
  },
}
